### ISSUE TITLE
API versions and runtime compatibility?

### ISSUE THREAD

**Issue by ringods** [ringods/go-xen-api-client#10]
I am slowly digging deeper in getting to know the XenAPI. By looking at the [xenapi.json](https://github.com/ringods/go-xen-api-client/blob/master/xenapi.json) file, I noticed that the lifecycle of all requests is fully documented.

Should we support adapting the go client api behavior to match the remote product version? Because now, what would happen if we connect this 7.2 compatible xenapi client library to e.g. a 6.0 XenServer?

I also noticed that `session.login_with_password` accepts the expected/required client API version as the 3rd argument. If we specify an older version, say `7.0`, should a `7.2` server return answers in `7.0` structure?

/cc @mborodin

**Comment by briantopping** [comment]
How would you propose that this was done? I can only imagine this is manageable through a full generation of `xxx_gen.go` for each `xenapi.json`, one for each supported version, potentially into a new package for each. The session would maintain the version and then use that reflectively to find the right generated code?

**Comment by ringods** [comment]
Closing this one as this would make the code base way to complicated.
