### ISSUE TITLE
Transfer ownership to `ringods` (me)

### ISSUE THREAD

**Issue by ringods** [ringods/go-xen-api-client#5]
Hello @amfranz, as you proposed in an [earlier pull request comment](https://github.com/amfranz/terraform-provider-xenserver/pull/3#issuecomment-327073966), you were willing to transfer ownership. As I don't get any feedback from the Xen community so far, I suggest that you start with transferring ownership to me. I'll create a request for transfor for the provider repo itself later, after you had time to merge https://github.com/amfranz/terraform-provider-xenserver/pull/10

**Comment by ringods** [comment]
@amfranz can you initiate the transfer of ownership please?

**Comment by amfranz** [comment]
I apologize, somehow I missed the initial notification.

Of course. Transfer underway. Take good care of the project :)
