### ISSUE TITLE
How to regenerate this library?

### ISSUE THREAD

**Issue by ringods** [ringods/go-xen-api-client#8]
The `README.md` file mentions this at the bottom of the file:

> Most of the code in this library is generated from a description of the XenAPI.

But I'm missing further information on how to regenerate the sources for a newer `xenapi.json` file. @amfranz could you create a small PR with an update of the `README.md` file explaining how to do this?

**Comment by mborodin** [comment]
@ringods just run `go generate`
I will create PR
